[package]
name = "clubfridge-neo"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "=1.0.95"
clap = { version = "=4.5.27", features = ["derive"] }
iced = { version = "=0.13.1", default-features = false, features = ["tokio", "wgpu"] }
jiff = "=0.1.28"
rust_decimal = "=1.36.0"
rust_decimal_macros = "=1.36.0"
serde = { version = "=1.0.217", features = ["derive"] }
serde_json = "=1.0.137"
tokio = { version = "=1.43.0", features = ["time"] }

[dev-dependencies]
tokio = { version = "=1.43.0", features = ["macros"] }
