name: CI

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: cargo clippy --workspace --all-targets --all-features -- --deny warnings --allow unknown_lints
      - run: cargo fmt --all --check

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}


      - run: cargo test --workspace --all-targets --all-features

  cross-build:
    runs-on: ubuntu-22.04
    env:
      # see https://woodruffw.github.io/zizmor/audits/#template-injection
      REF_NAME: ${{ github.ref_name }}
      # renovate: datasource=crate depName=cross versioning=semver
      CROSS_VERSION: 0.2.5
      TARGET_ARCH: aarch64-unknown-linux-gnu
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: cargo install cross --vers ${CROSS_VERSION}
      - run: cross build --release --target=${TARGET_ARCH}

      - run: cp target/${TARGET_ARCH}/release/clubfridge-neo clubfridge-neo
      - run: tar czf clubfridge-neo-${REF_NAME}-${TARGET_ARCH}.tar.gz clubfridge-neo

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: clubfridge-neo-${{ env.REF_NAME }}-${{ env.TARGET_ARCH }}.tar.gz
          path: clubfridge-neo-${{ env.REF_NAME }}-${{ env.TARGET_ARCH }}.tar.gz

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: clubfridge-neo-${{ env.REF_NAME }}-${{ env.TARGET_ARCH }}.tar.gz
