name: CI

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: cargo clippy --workspace --all-targets --all-features -- --deny warnings --allow unknown_lints
      - run: cargo fmt --all --check

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}


      - run: cargo test --workspace --all-targets --all-features

  cross-build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    env:
      # see https://woodruffw.github.io/zizmor/audits/#template-injection
      REF_NAME: ${{ github.ref_name }}
      # renovate: datasource=crate depName=cross versioning=semver
      CROSS_VERSION: 0.2.5
      TARGET_ARCH: aarch64-unknown-linux-gnu
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: cargo install cross --vers ${CROSS_VERSION}
      - run: cross build --release --target=${TARGET_ARCH}

      - run: cp target/${TARGET_ARCH}/release/clubfridge-neo clubfridge-neo
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'

      - run: tar czf clubfridge-neo-${REF_NAME}-${TARGET_ARCH}.tar.gz clubfridge-neo
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        with:
          name: clubfridge-neo-${{ env.REF_NAME }}-${{ env.TARGET_ARCH }}.tar.gz
          path: clubfridge-neo-${{ env.REF_NAME }}-${{ env.TARGET_ARCH }}.tar.gz

      - uses: softprops/action-gh-release@62c96d0c4e8a889135c1f3a25910db8dbe0e85f7 # v2.3.4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: clubfridge-neo-${{ env.REF_NAME }}-${{ env.TARGET_ARCH }}.tar.gz
